steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - id: 'render-app-yaml'
    name: 'gcr.io/cloud-builders-community/envsubst'
    args: ['api.yaml']
    env:
      - 'SECRET_KEY=${_SECRET_KEY}'
      - 'MONGODB_URI=${_MURI}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'api.yaml', '-v', '$_GAE_VERSION']
timeout: '1600s'
